---

- hosts: all
  become: true
  tasks:
  - name: install apache2 and php packages
    tags: apache,php 
    apt:
      name:
        - "{{ apache2_package }}" 
        - "{{ php_package }}"
      state: latest
  - name: copy default html file for site 
    tags: apache
    copy:
       src: default_site.html
       dest: /var/www/html/index.html
       owner: root
       group: root 
       mode: 0644
  - name: add ssh key for user(alla)
    tags: always
    authorized_key:
         user: alla 
         key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMC8gqZwBlDpJ6nvEMECN1xAkDnUzVuvYLgpDvU3azij ansible"
- hosts: web-server
  become: true
  tasks:
  - name: install db
    apt: 
      name: mariadb-server
      state: latest   
