---

- hosts: all
  become: true
  tasks:
  - name: install apache2 and php packages
    tags: apache,php 
    apt:
      name:
        - "{{ apache2_package }}" 
        - "{{ php_package }}"
      state: latest
  - name: copy default html file for site 
    tags: apache
    copy:
       src: default_site.html
       dest: /var/www/html/index.html
       owner: root
       group: root 
       mode: 0644
