---

- hosts: all
  become: true
  tasks:
  - name: install apache2 and php packages
    tags: apache,php 
    apt:
      name:
        - "{{ apache2_package }}" 
        - "{{ php_package }}"
      state: latest
