---

- hosts: all
  become: true
  tasks:
  - name: install apache2 and php packages
    tags: apache,php 
    apt:
      name:
        - "{{ apache2_package }}" 
        - "{{ php_package }}"
      state: latest
  - name: copy default html file for site 
    tags: apache
    copy:
       src: default_site.html
       dest: /var/www/html/index.html
       owner: root
       group: root 
       mode: 0644
- hosts: workstation
  become: true
  tasks:

  - name: install unzip
    package:
      name: unzip 
  - name: install terraform
    unarchive:
       src: https://releases.hashicorp.com/terraform/0.12.28/terraform_0.12.28_linux_amd64.zip
       dest: /usr/local/bin
       remote_src: yes
       mode: 0755
       owner: root
       group: root 
