---

- hosts: all
  become: true
  tasks:
  - name: install apache2 and php packages
    tags: apache,php 
    apt:
      name: apache2
      state: latest
- hosts: all
  become: true
  roles:
      - base
- hosts: web-server
  become: true
  roles:
      - web-server
