---

- hosts: all
  become: true
  tasks:
  - name: install apache2 and php packages
    tags: apache,php 
    apt:
      name:
        - "{{ apache2_package }}" 
        - "{{ php_package }}"
      state: latest
  
  - name: changing email for alla file
    tags: apache
    lineinfile: 
        path: /home/lubana11/alla
        regexp: '^email'
        line: email alla36@gmail.com
    register: httpd
  - name: restart httpd
    service:
        name: httpd
        state: restarted
    when: httpd.changed
- hosts: all
  become: true
  roles:
      - base
- hosts: web-server
  become: true
  roles:
      - web-server
